### ISSUE TITLE
Db Install problem

### ISSUE THREAD

**Issue by minasvisual** [iherwig/wcmf#17] opened 2018-10-18 19:03 UTC
I get this error when try install data after migrate tables:
[2018-10-18 19:02:23] INFO: install:42: initializing wCMF database tables...
[2018-10-18 19:02:23] INFO: wcmf\lib\util\DBUtil:91: Executing SQL script C:/wamp/www/testes/wcmf/wcmf-default-app/install/custom-install/database_1.sql ...
[2018-10-18 19:02:23] INFO: wcmf\lib\persistence\impl\DefaultTransaction:84: Starting transaction
[2018-10-18 19:02:23] INFO: install:69: creating role with name 'administrators'...
[2018-10-18 19:02:23] INFO: install:75: creating user with login 'admin' password 'admin'...
[2018-10-18 19:02:23] ERROR: install:95: Invalid value (1) for super_user: The super user property can only be changed by super users
[2018-10-18 19:02:23] INFO: wcmf\lib\persistence\impl\DefaultTransaction:108: Rollback transaction

Can you help me?

**Comment by iherwig** [comment] 2018-10-19 07:20
hi minasvisual! Thank you for reporting this problem. I will have a look.

**Comment by iherwig** [comment] 2018-10-21 21:33
The issue is fixed in latest wcmf release (4.1.19). Call `composer update` in the wcmf-default-app project to update to this release. Please re-open this issue, if it does not work for you.

**Closed as completed by iherwig** 2018-10-21 21:33 UTC
Labels: bug
